name: Archive tests

on:
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build and Test
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from Github
        uses: actions/checkout@v2
      
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
  
      - name: Build and Test
        run: |
          cd archive_service
          sbt -v +test