name: Tests

on:
  push:
    branches: 
      - main
    # paths:
    #   - 'ocr_service/**'

  pull_request:
    branches: 
      - main
    # paths:
    #   - 'ocr_service/**'

jobs:
  build:
    name: Build and Test
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from Github
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
        
      - name: Run tests with Maven
        run: |
          cd ocr_service
          mvn -B test --file pom.xml