name: Text analyzer tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd textAnalyzer
        dotnet restore
    - name: Build
      run: |
        cd textAnalyzer
        dotnet build --no-restore
    - name: Test
      run: |
        cd textAnalyzer      
        dotnet test --no-build --verbosity normal